# -*- coding: utf-8 -*-
"""GPT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R7C2uhIW3KrsG-BTE0dufOW2xjQGLHqz
"""

import streamlit as st
from openai import OpenAI
import os

# In Colab, we can use user_secret for the key or hardcode it for a quick test
# Warning: Do not share the link if you hardcode your key!
client = OpenAI(api_key="sk-1234567890abcdef1234567890abcdef12345678")

st.title("GPT App ")

user_input = st.text_input("Ask me anything:")

if st.button("Send") and user_input:
    try:
        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[{"role": "user", "content": user_input}]
        )
        st.write(response.choices[0].message.content)
    except Exception as e:
        st.error(f"Error: {e}")